
package com.bookingws.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccomodationServicePort", targetNamespace = "http://bookingws.com/soap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccomodationServicePort {


    /**
     * 
     * @param setCountryRequest
     * @return
     *     returns com.bookingws.soap.SetCountryResponse
     */
    @WebMethod
    @WebResult(name = "setCountryResponse", targetNamespace = "http://bookingws.com/soap", partName = "setCountryResponse")
    public SetCountryResponse setCountry(
        @WebParam(name = "setCountryRequest", targetNamespace = "http://bookingws.com/soap", partName = "setCountryRequest")
        SetCountryRequest setCountryRequest);

    /**
     * 
     * @param getCountriesRequest
     * @return
     *     returns com.bookingws.soap.GetCountriesResponse
     */
    @WebMethod
    @WebResult(name = "getCountriesResponse", targetNamespace = "http://bookingws.com/soap", partName = "getCountriesResponse")
    public GetCountriesResponse getCountries(
        @WebParam(name = "getCountriesRequest", targetNamespace = "http://bookingws.com/soap", partName = "getCountriesRequest")
        GetCountriesRequest getCountriesRequest);

    /**
     * 
     * @param getCountryRequest
     * @return
     *     returns com.bookingws.soap.GetCountryResponse
     */
    @WebMethod
    @WebResult(name = "getCountryResponse", targetNamespace = "http://bookingws.com/soap", partName = "getCountryResponse")
    public GetCountryResponse getCountry(
        @WebParam(name = "getCountryRequest", targetNamespace = "http://bookingws.com/soap", partName = "getCountryRequest")
        GetCountryRequest getCountryRequest);

    /**
     * 
     * @param getCategoriesRequest
     * @return
     *     returns com.bookingws.soap.GetCategoriesResponse
     */
    @WebMethod
    @WebResult(name = "getCategoriesResponse", targetNamespace = "http://bookingws.com/soap", partName = "getCategoriesResponse")
    public GetCategoriesResponse getCategories(
        @WebParam(name = "getCategoriesRequest", targetNamespace = "http://bookingws.com/soap", partName = "getCategoriesRequest")
        GetCategoriesRequest getCategoriesRequest);

    /**
     * 
     * @param addAccomodationRequest
     * @return
     *     returns com.bookingws.soap.AddAccomodationResponse
     */
    @WebMethod
    @WebResult(name = "addAccomodationResponse", targetNamespace = "http://bookingws.com/soap", partName = "addAccomodationResponse")
    public AddAccomodationResponse addAccomodation(
        @WebParam(name = "addAccomodationRequest", targetNamespace = "http://bookingws.com/soap", partName = "addAccomodationRequest")
        AddAccomodationRequest addAccomodationRequest);

    /**
     * 
     * @param getTypesAccomodationRequest
     * @return
     *     returns com.bookingws.soap.GetTypesAccomodationResponse
     */
    @WebMethod
    @WebResult(name = "getTypesAccomodationResponse", targetNamespace = "http://bookingws.com/soap", partName = "getTypesAccomodationResponse")
    public GetTypesAccomodationResponse getTypesAccomodation(
        @WebParam(name = "getTypesAccomodationRequest", targetNamespace = "http://bookingws.com/soap", partName = "getTypesAccomodationRequest")
        GetTypesAccomodationRequest getTypesAccomodationRequest);

    /**
     * 
     * @param getCitiesRequest
     * @return
     *     returns com.bookingws.soap.GetCitiesResponse
     */
    @WebMethod
    @WebResult(name = "getCitiesResponse", targetNamespace = "http://bookingws.com/soap", partName = "getCitiesResponse")
    public GetCitiesResponse getCities(
        @WebParam(name = "getCitiesRequest", targetNamespace = "http://bookingws.com/soap", partName = "getCitiesRequest")
        GetCitiesRequest getCitiesRequest);

}
