
package com.bookingws.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccomodationServicePort", targetNamespace = "http://bookingws.com/soap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccomodationServicePort {


    /**
     * 
     * @param getCountriesRequest
     * @return
     *     returns com.bookingws.soap.GetCountriesResponse
     */
    @WebMethod
    @WebResult(name = "getCountriesResponse", targetNamespace = "http://bookingws.com/soap", partName = "getCountriesResponse")
    public GetCountriesResponse getCountries(
        @WebParam(name = "getCountriesRequest", targetNamespace = "http://bookingws.com/soap", partName = "getCountriesRequest")
        GetCountriesRequest getCountriesRequest);

    /**
     * 
     * @param setCountryRequest
     * @return
     *     returns com.bookingws.soap.SetCountryResponse
     */
    @WebMethod
    @WebResult(name = "setCountryResponse", targetNamespace = "http://bookingws.com/soap", partName = "setCountryResponse")
    public SetCountryResponse setCountry(
        @WebParam(name = "setCountryRequest", targetNamespace = "http://bookingws.com/soap", partName = "setCountryRequest")
        SetCountryRequest setCountryRequest);

    /**
     * 
     * @param getCountryRequest
     * @return
     *     returns com.bookingws.soap.GetCountryResponse
     */
    @WebMethod
    @WebResult(name = "getCountryResponse", targetNamespace = "http://bookingws.com/soap", partName = "getCountryResponse")
    public GetCountryResponse getCountry(
        @WebParam(name = "getCountryRequest", targetNamespace = "http://bookingws.com/soap", partName = "getCountryRequest")
        GetCountryRequest getCountryRequest);

}
