
package com.bookingws.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccomodationService", targetNamespace = "http://bookingws.com/soap", wsdlLocation = "http://localhost:8000/soapWs/accomodation.wsdl")
public class AccomodationService
    extends Service
{

    private final static URL ACCOMODATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOMODATIONSERVICE_EXCEPTION;
    private final static QName ACCOMODATIONSERVICE_QNAME = new QName("http://bookingws.com/soap", "AccomodationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/soapWs/accomodation.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOMODATIONSERVICE_WSDL_LOCATION = url;
        ACCOMODATIONSERVICE_EXCEPTION = e;
    }

    public AccomodationService() {
        super(__getWsdlLocation(), ACCOMODATIONSERVICE_QNAME);
    }

    public AccomodationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOMODATIONSERVICE_QNAME, features);
    }

    public AccomodationService(URL wsdlLocation) {
        super(wsdlLocation, ACCOMODATIONSERVICE_QNAME);
    }

    public AccomodationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOMODATIONSERVICE_QNAME, features);
    }

    public AccomodationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccomodationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccomodationServicePort
     */
    @WebEndpoint(name = "AccomodationServicePortSoap11")
    public AccomodationServicePort getAccomodationServicePortSoap11() {
        return super.getPort(new QName("http://bookingws.com/soap", "AccomodationServicePortSoap11"), AccomodationServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccomodationServicePort
     */
    @WebEndpoint(name = "AccomodationServicePortSoap11")
    public AccomodationServicePort getAccomodationServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://bookingws.com/soap", "AccomodationServicePortSoap11"), AccomodationServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOMODATIONSERVICE_EXCEPTION!= null) {
            throw ACCOMODATIONSERVICE_EXCEPTION;
        }
        return ACCOMODATIONSERVICE_WSDL_LOCATION;
    }

}
